In [42]:
#!pip install nbformat

In [43]:
import pandas as pd
import plotly.express as px

In [44]:
dados = pd.read_csv('telecom_users.csv')
dados.head(5)

,Unnamed: 0,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,1869,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,4528,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,6344,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6739,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,432,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN

In [45]:
dados = dados.drop('Unnamed: 0', axis=1) # Removendo a coluna 'Unnamed: 0'
dados

,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,Nao,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,Nao,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,Nao,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,Sim,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,0684-AOSIH,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,Sim,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95,Sim,NaN
5982,5982-PSMKW,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,Sim,...,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.3,Nao,NaN
5983,8044-BGWPI,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao,NaN
5984,7450-NWRTR,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,Nao,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim,NaN
5985,4795-UXVCJ,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.3,Nao,NaN

In [46]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5986 non-null   object
 1   Genero                  5986 non-null   object
 2   Aposentado              5986 non-null   int64
 3   Casado                  5986 non-null   object
 4   Dependentes             5985 non-null   object
 5   MesesComoCliente        5986 non-null   int64
 6   ServicoTelefone         5986 non-null   object
 7   MultiplasLinhas         5986 non-null   object
 8   ServicoInternet         5986 non-null   object
 9   ServicoSegurancaOnline  5986 non-null   object
 10  ServicoBackupOnline     5986 non-null   object
 11  ProtecaoEquipamento     5986 non-null   object
 12  ServicoSuporteTecnico   5986 non-null   object
 13  ServicoStreamingTV      5986 non-null   object
 14  ServicoFilmes           5986 non-null   object
 15  TipoContrato            5986 non-null   object
 16  FaturaDigital           5986 non-null   object
 17  FormaPagamento          5986 non-null   object
 18  ValorMensal             5986 non-null   float64
 19  TotalGasto              5986 non-null   object
 20  Churn                   5985 non-null   object
 21  Codigo                  0 non-null      float64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.0+ MB

In [47]:
dados.TotalGasto = pd.to_numeric(dados.TotalGasto, errors = 'coerce') # transformando valores que sÃ£o numeros mas o python entendeu como texto
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5986 non-null   object
 1   Genero                  5986 non-null   object
 2   Aposentado              5986 non-null   int64
 3   Casado                  5986 non-null   object
 4   Dependentes             5985 non-null   object
 5   MesesComoCliente        5986 non-null   int64
 6   ServicoTelefone         5986 non-null   object
 7   MultiplasLinhas         5986 non-null   object
 8   ServicoInternet         5986 non-null   object
 9   ServicoSegurancaOnline  5986 non-null   object
 10  ServicoBackupOnline     5986 non-null   object
 11  ProtecaoEquipamento     5986 non-null   object
 12  ServicoSuporteTecnico   5986 non-null   object
 13  ServicoStreamingTV      5986 non-null   object
 14  ServicoFilmes           5986 non-null   object
 15  TipoContrato            5986 non-null   object
 16  FaturaDigital           5986 non-null   object
 17  FormaPagamento          5986 non-null   object
 18  ValorMensal             5986 non-null   float64
 19  TotalGasto              5976 non-null   float64
 20  Churn                   5985 non-null   object
 21  Codigo                  0 non-null      float64
dtypes: float64(3), int64(2), object(17)
memory usage: 1.0+ MB

In [48]:
dados = dados.dropna(how = 'all', axis = 1) # removendo colunas completamente vazias
dados = dados.dropna(how = 'any', axis = 0) # removendo linha com pelo menos 1 valor vazio
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5974 entries, 0 to 5985
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5974 non-null   object
 1   Genero                  5974 non-null   object
 2   Aposentado              5974 non-null   int64
 3   Casado                  5974 non-null   object
 4   Dependentes             5974 non-null   object
 5   MesesComoCliente        5974 non-null   int64
 6   ServicoTelefone         5974 non-null   object
 7   MultiplasLinhas         5974 non-null   object
 8   ServicoInternet         5974 non-null   object
 9   ServicoSegurancaOnline  5974 non-null   object
 10  ServicoBackupOnline     5974 non-null   object
 11  ProtecaoEquipamento     5974 non-null   object
 12  ServicoSuporteTecnico   5974 non-null   object
 13  ServicoStreamingTV      5974 non-null   object
 14  ServicoFilmes           5974 non-null   object
 15  TipoContrato            5974 non-null   object
 16  FaturaDigital           5974 non-null   object
 17  FormaPagamento          5974 non-null   object
 18  ValorMensal             5974 non-null   float64
 19  TotalGasto              5974 non-null   float64
 20  Churn                   5974 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.0+ MB

In [49]:
dados.Churn.value_counts()

Nao    4387
Sim    1587
Name: Churn, dtype: int64

In [50]:
dados.Churn.value_counts(normalize = True).map('{:.1%}'.format)

Nao    73.4%
Sim    26.6%
Name: Churn, dtype: object

In [51]:
for coluna in dados.columns:
    grafico = px.histogram(dados, x = coluna, color = 'Churn')
    grafico.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed